### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by adrianne-helpscout**
Adding link to support via the Help Scout support queue.

### CODE REVIEW

**Review by ScottPetit — APPROVED** [review]
👍

**Review by codenameDuchess — APPROVED** [review]
💯

**Comment by adrianne-helpscout** [comment]
@ScottPetit and @codenameDuchess I added a suggestion that @aliripe suggested on my other [PR for the Android repo ](https://github.com/helpscout/beacon-android-sdk-sample/pull/181), basically adding an issue template to the mailto. I really like this suggestion and am probably going to apply it to our developer docs as well. 👍  I'd <3 for you to take another peek before I commit.

**Review by ScottPetit — APPROVED** [review]
👍 Gave the link a test and worked as expected

**Comment by adrianne-helpscout** [comment]
Just realized that @codenameDuchess is out today; so, I'm going to merge with @ScottPetit second set of eyes.

**Pull request merged**
